#!/usr/bin/env python3
"""Generates packaging/version_info.txt — the Windows VERSIONINFO resource.

This is what fills in the Details tab of the .exe's Properties dialog, and
what Windows and most software inventories read to identify the program.
An executable without it looks anonymous and untrustworthy, and some
corporate deployment tools refuse to catalogue one.

Generated rather than hand-maintained so it can never disagree with
app/__version__.py, which is the single source of the version number.

    python packaging/make_version_info.py

Run by the build before PyInstaller; the .spec references the output.
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from app.__version__ import APP_NAME, ORG_NAME, VERSION  # noqa: E402

OUTPUT = Path(__file__).resolve().parent / "version_info.txt"

TEMPLATE = """# Generated by packaging/make_version_info.py — do not edit by hand.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers=({major}, {minor}, {patch}, 0),
    prodvers=({major}, {minor}, {patch}, 0),
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo([
      StringTable(
        '040904B0',
        [StringStruct('CompanyName', {company!r}),
         StringStruct('FileDescription', {description!r}),
         StringStruct('FileVersion', {version!r}),
         StringStruct('InternalName', {internal!r}),
         StringStruct('OriginalFilename', {filename!r}),
         StringStruct('ProductName', {product!r}),
         StringStruct('ProductVersion', {version!r})])
    ]),
    # 1033 = US English, 1200 = UTF-16. Must match the '040904B0' above.
    VarFileInfo([VarStruct('Translation', [1033, 1200])])
  ]
)
"""


def main() -> int:
    try:
        major, minor, patch = (int(part) for part in VERSION.split("."))
    except ValueError:
        raise SystemExit(
            f"VERSION must be 'major.minor.patch' with integer parts, got {VERSION!r}. "
            "Windows VERSIONINFO cannot represent a suffix like '-rc1'.") from None

    OUTPUT.write_text(TEMPLATE.format(
        major=major, minor=minor, patch=patch,
        company=ORG_NAME,
        description=APP_NAME,
        version=VERSION,
        internal="InventoryManagementSystem",
        filename="InventoryManagementSystem.exe",
        product=APP_NAME,
    ), encoding="utf-8")
    print(f"Wrote {OUTPUT} for version {VERSION}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
