"""add settings module columns and purchase order numbering

Revision ID: 222422423b7c
Revises: 3129d385a553
Create Date: 2026-08-14 18:55:18.477514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '222422423b7c'
down_revision: Union[str, None] = '3129d385a553'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase_order_sequences',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('next_value', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('organization_id')
    )
    op.add_column('organizations', sa.Column('logo_image', sa.LargeBinary(), nullable=True))
    op.add_column('organizations', sa.Column('logo_content_type', sa.String(length=100), nullable=True))
    op.add_column('organizations', sa.Column('default_warehouse_id', sa.UUID(), nullable=True))
    # add_column (unlike a fresh CREATE TABLE) does not implicitly create
    # the Postgres enum type a sa.Enum column needs — has to be done
    # explicitly first, or the ALTER TABLE below fails with "type ... does
    # not exist".
    sa.Enum('WARN_ONLY', 'BLOCK_SALE', name='low_stock_behavior').create(
        op.get_bind(), checkfirst=True)
    sa.Enum('FIFO', 'LIFO', 'WEIGHTED_AVERAGE', name='stock_valuation_method').create(
        op.get_bind(), checkfirst=True)
    sa.Enum('MANUAL', 'DAILY', 'WEEKLY', name='backup_frequency').create(
        op.get_bind(), checkfirst=True)
    # server_default on every NOT NULL column below: the real database
    # already has organization rows before this migration runs, and a
    # bare `nullable=False` with no default would fail against them (same
    # fix applied to every prior migration adding a NOT NULL column to a
    # live table — see e.g. 8e90faa79337).
    op.add_column('organizations', sa.Column('low_stock_behavior', sa.Enum('WARN_ONLY', 'BLOCK_SALE', name='low_stock_behavior'), nullable=False, server_default='WARN_ONLY'))
    op.add_column('organizations', sa.Column('stock_valuation_method', sa.Enum('FIFO', 'LIFO', 'WEIGHTED_AVERAGE', name='stock_valuation_method'), nullable=False, server_default='WEIGHTED_AVERAGE'))
    op.add_column('organizations', sa.Column('default_tax_percent', sa.Numeric(precision=5, scale=2), nullable=False, server_default='0'))
    op.add_column('organizations', sa.Column('default_discount_percent', sa.Numeric(precision=5, scale=2), nullable=False, server_default='0'))
    op.add_column('organizations', sa.Column('purchase_number_prefix', sa.String(length=20), nullable=False, server_default='PO-'))
    op.add_column('organizations', sa.Column('session_timeout_minutes', sa.Integer(), nullable=False, server_default='30'))
    op.add_column('organizations', sa.Column('password_min_length', sa.Integer(), nullable=False, server_default='8'))
    op.add_column('organizations', sa.Column('password_require_uppercase', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('organizations', sa.Column('password_require_number', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('organizations', sa.Column('password_require_special_char', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('organizations', sa.Column('backup_directory', sa.String(length=1000), nullable=True))
    op.add_column('organizations', sa.Column('backup_frequency', sa.Enum('MANUAL', 'DAILY', 'WEEKLY', name='backup_frequency'), nullable=False, server_default='MANUAL'))
    op.add_column('organizations', sa.Column('backup_retention_count', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_organizations_default_warehouse_id_warehouses', 'organizations', 'warehouses', ['default_warehouse_id'], ['id'], ondelete='RESTRICT')
    op.create_check_constraint('ck_organizations_backup_retention_non_negative', 'organizations', 'backup_retention_count IS NULL OR backup_retention_count >= 0')
    op.create_check_constraint('ck_organizations_default_discount_percent_range', 'organizations', 'default_discount_percent >= 0 AND default_discount_percent <= 100')
    op.create_check_constraint('ck_organizations_default_tax_percent_range', 'organizations', 'default_tax_percent >= 0 AND default_tax_percent <= 100')
    op.create_check_constraint('ck_organizations_password_min_length_floor', 'organizations', 'password_min_length >= 4')
    op.create_check_constraint('ck_organizations_session_timeout_positive', 'organizations', 'session_timeout_minutes > 0')
    op.add_column('purchase_orders', sa.Column('order_number', sa.String(length=40), nullable=True))
    op.create_index('ix_purchase_orders_org_order_number', 'purchase_orders', ['organization_id', 'order_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_purchase_orders_org_order_number', table_name='purchase_orders')
    op.drop_column('purchase_orders', 'order_number')
    op.drop_constraint('ck_organizations_session_timeout_positive', 'organizations', type_='check')
    op.drop_constraint('ck_organizations_password_min_length_floor', 'organizations', type_='check')
    op.drop_constraint('ck_organizations_default_tax_percent_range', 'organizations', type_='check')
    op.drop_constraint('ck_organizations_default_discount_percent_range', 'organizations', type_='check')
    op.drop_constraint('ck_organizations_backup_retention_non_negative', 'organizations', type_='check')
    op.drop_constraint('fk_organizations_default_warehouse_id_warehouses', 'organizations', type_='foreignkey')
    op.drop_column('organizations', 'backup_retention_count')
    op.drop_column('organizations', 'backup_frequency')
    op.drop_column('organizations', 'backup_directory')
    op.drop_column('organizations', 'password_require_special_char')
    op.drop_column('organizations', 'password_require_number')
    op.drop_column('organizations', 'password_require_uppercase')
    op.drop_column('organizations', 'password_min_length')
    op.drop_column('organizations', 'session_timeout_minutes')
    op.drop_column('organizations', 'purchase_number_prefix')
    op.drop_column('organizations', 'default_discount_percent')
    op.drop_column('organizations', 'default_tax_percent')
    op.drop_column('organizations', 'stock_valuation_method')
    op.drop_column('organizations', 'low_stock_behavior')
    op.drop_column('organizations', 'default_warehouse_id')
    op.drop_column('organizations', 'logo_content_type')
    op.drop_column('organizations', 'logo_image')
    op.drop_table('purchase_order_sequences')
    # Adjusted by hand: drop_column() does not drop the Postgres native
    # enum types it created — without this, re-running upgrade after this
    # downgrade fails with "type ... already exists" (same fix as
    # purchase_order_status in ae0be6ce7951 / backup_status in 3129d385a553).
    sa.Enum(name='backup_frequency').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='stock_valuation_method').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='low_stock_behavior').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
