"""add customer code, type, address detail, credit control, created_by

Revision ID: 65a248c62115
Revises: c08912894e62
Create Date: 2026-08-15 09:59:34.761839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65a248c62115'
down_revision: Union[str, None] = 'c08912894e62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    customer_type_enum = sa.Enum('INDIVIDUAL', 'BUSINESS', name='customer_type')
    customer_type_enum.create(op.get_bind())

    op.add_column('customers', sa.Column('customer_code', sa.String(length=50), nullable=True))
    op.add_column('customers', sa.Column(
        'customer_type', customer_type_enum,
        nullable=False, server_default='INDIVIDUAL'))
    op.add_column('customers', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('customers', sa.Column('state', sa.String(length=100), nullable=True))
    op.add_column('customers', sa.Column('country', sa.String(length=100), nullable=True))
    op.add_column('customers', sa.Column('credit_limit', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('customers', sa.Column(
        'opening_balance', sa.Numeric(precision=12, scale=2), nullable=False,
        server_default='0'))
    op.add_column('customers', sa.Column('created_by', sa.UUID(), nullable=True))

    # Backfill a generated code for any customer that predates this column
    # (existing installs) — new rows always get one from
    # SalesService.create_customer, so this only ever runs once, here.
    op.execute(
        "UPDATE customers SET customer_code = 'CUST-' || upper(substr(id::text, 1, 8)) "
        "WHERE customer_code IS NULL")

    op.create_index('ix_customers_org_code', 'customers', ['organization_id', 'customer_code'], unique=True)
    op.create_foreign_key(None, 'customers', 'users', ['created_by'], ['id'], ondelete='RESTRICT')
    op.create_check_constraint('ck_customers_credit_limit_non_negative', 'customers', 'credit_limit IS NULL OR credit_limit >= 0')
    op.create_check_constraint('ck_customers_opening_balance_non_negative', 'customers', 'opening_balance >= 0')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_customers_opening_balance_non_negative', 'customers', type_='check')
    op.drop_constraint('ck_customers_credit_limit_non_negative', 'customers', type_='check')
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.drop_index('ix_customers_org_code', table_name='customers')
    op.drop_column('customers', 'created_by')
    op.drop_column('customers', 'opening_balance')
    op.drop_column('customers', 'credit_limit')
    op.drop_column('customers', 'country')
    op.drop_column('customers', 'state')
    op.drop_column('customers', 'city')
    op.drop_column('customers', 'customer_type')
    op.drop_column('customers', 'customer_code')
    sa.Enum(name='customer_type').drop(op.get_bind())
    # ### end Alembic commands ###
