"""add warehouses and inventory ledger

Revision ID: 69ff54a9f513
Revises: c9791cffd8b9
Create Date: 2026-08-14 08:08:25.442063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69ff54a9f513'
down_revision: Union[str, None] = 'c9791cffd8b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warehouses',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('code = upper(code)', name='ck_warehouses_code_uppercase'),
    sa.CheckConstraint('length(trim(code)) > 0', name='ck_warehouses_code_not_blank'),
    sa.CheckConstraint('length(trim(name)) > 0', name='ck_warehouses_name_not_blank'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_warehouses_org_code', 'warehouses', ['organization_id', 'code'], unique=True)
    op.create_table('inventory',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('quantity_on_hand', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('quantity_reserved', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity_on_hand < 0 OR quantity_reserved <= quantity_on_hand', name='ck_inventory_reserved_not_exceed_on_hand'),
    sa.CheckConstraint('quantity_reserved >= 0', name='ck_inventory_reserved_non_negative'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_inventory_org_product_warehouse', 'inventory', ['organization_id', 'product_id', 'warehouse_id'], unique=True)
    op.create_index('ix_inventory_warehouse_id', 'inventory', ['warehouse_id'], unique=False)
    op.create_table('inventory_transactions',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('transaction_type', sa.Enum('STOCK_IN', 'PURCHASE_RECEIVED', 'STOCK_OUT', 'SALE', 'DAMAGE', 'RETURN_IN', 'RETURN_OUT', 'ADJUSTMENT', 'TRANSFER_OUT', 'TRANSFER_IN', 'RESERVE', 'RELEASE_RESERVE', name='inventory_transaction_type'), nullable=False),
    sa.Column('quantity_change', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('quantity_on_hand_after', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('quantity_reserved_after', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('reference_type', sa.String(length=32), nullable=True),
    sa.Column('reference_id', sa.UUID(), nullable=True),
    sa.Column('performed_by', sa.UUID(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('quantity_change != 0', name='ck_inventory_tx_quantity_nonzero'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_inventory_tx_org_product_warehouse_created', 'inventory_transactions', ['organization_id', 'product_id', 'warehouse_id', 'created_at'], unique=False)
    op.create_index('ix_inventory_tx_org_type', 'inventory_transactions', ['organization_id', 'transaction_type'], unique=False)
    op.create_index('ix_inventory_tx_reference', 'inventory_transactions', ['reference_type', 'reference_id'], unique=False)
    op.create_table('stock_adjustments',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('quantity_change', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('performed_by', sa.UUID(), nullable=False),
    sa.Column('inventory_transaction_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('length(trim(reason)) > 0', name='ck_stock_adjustments_reason_not_blank'),
    sa.CheckConstraint('quantity_change != 0', name='ck_stock_adjustments_quantity_nonzero'),
    sa.ForeignKeyConstraint(['inventory_transaction_id'], ['inventory_transactions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inventory_transaction_id')
    )
    op.create_index('ix_stock_adjustments_org_product_warehouse', 'stock_adjustments', ['organization_id', 'product_id', 'warehouse_id'], unique=False)
    op.create_table('stock_transfers',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('from_warehouse_id', sa.UUID(), nullable=False),
    sa.Column('to_warehouse_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('performed_by', sa.UUID(), nullable=False),
    sa.Column('out_transaction_id', sa.UUID(), nullable=False),
    sa.Column('in_transaction_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('from_warehouse_id != to_warehouse_id', name='ck_stock_transfers_distinct_warehouses'),
    sa.CheckConstraint('quantity > 0', name='ck_stock_transfers_quantity_positive'),
    sa.ForeignKeyConstraint(['from_warehouse_id'], ['warehouses.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['in_transaction_id'], ['inventory_transactions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['out_transaction_id'], ['inventory_transactions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['to_warehouse_id'], ['warehouses.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('in_transaction_id'),
    sa.UniqueConstraint('out_transaction_id')
    )
    op.create_index('ix_stock_transfers_org_product', 'stock_transfers', ['organization_id', 'product_id'], unique=False)
    # Adjusted by hand: autogenerate can't know this table already has rows
    # in a real deployment — a NOT NULL column added with no default would
    # fail on every existing row. server_default matches the ORM model's
    # client-side default=False.
    op.add_column('organizations', sa.Column('allow_negative_stock', sa.Boolean(),
                                              server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'allow_negative_stock')
    op.drop_index('ix_stock_transfers_org_product', table_name='stock_transfers')
    op.drop_table('stock_transfers')
    op.drop_index('ix_stock_adjustments_org_product_warehouse', table_name='stock_adjustments')
    op.drop_table('stock_adjustments')
    op.drop_index('ix_inventory_tx_reference', table_name='inventory_transactions')
    op.drop_index('ix_inventory_tx_org_type', table_name='inventory_transactions')
    op.drop_index('ix_inventory_tx_org_product_warehouse_created', table_name='inventory_transactions')
    op.drop_table('inventory_transactions')
    # Adjusted by hand: drop_table() does not drop the Postgres native enum
    # type it created — without this, re-running upgrade after this
    # downgrade fails with "type inventory_transaction_type already exists"
    # (same fix as product_status in c9791cffd8b9).
    sa.Enum(name='inventory_transaction_type').drop(op.get_bind(), checkfirst=True)
    op.drop_index('ix_inventory_warehouse_id', table_name='inventory')
    op.drop_index('ix_inventory_org_product_warehouse', table_name='inventory')
    op.drop_table('inventory')
    op.drop_index('ix_warehouses_org_code', table_name='warehouses')
    op.drop_table('warehouses')
    # ### end Alembic commands ###
