"""add discount_percent to sales_order_items and discount_amount to invoices

Revision ID: 8e90faa79337
Revises: b6ce0b34f974
Create Date: 2026-08-14 09:28:31.852954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e90faa79337'
down_revision: Union[str, None] = 'b6ce0b34f974'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Adjusted by hand: both tables already have rows in a real deployment
    # (invoices generated / order items created before this migration) —
    # NOT NULL columns with no default would fail on every existing row.
    # server_default matches each ORM model's client-side default=0.
    op.add_column('invoices', sa.Column('discount_amount', sa.Numeric(precision=12, scale=2),
                                        server_default='0', nullable=False))
    op.create_check_constraint('ck_invoices_discount_amount_non_negative', 'invoices', 'discount_amount >= 0')
    op.add_column('sales_order_items', sa.Column('discount_percent', sa.Numeric(precision=5, scale=2),
                                                  server_default='0', nullable=False))
    op.create_check_constraint('ck_so_items_discount_percent_range', 'sales_order_items', 'discount_percent >= 0 AND discount_percent <= 100')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_so_items_discount_percent_range', 'sales_order_items', type_='check')
    op.drop_column('sales_order_items', 'discount_percent')
    op.drop_constraint('ck_invoices_discount_amount_non_negative', 'invoices', type_='check')
    op.drop_column('invoices', 'discount_amount')
    # ### end Alembic commands ###
