"""add product type, units hierarchy, and attributes to products

Revision ID: aa93d2683eaa
Revises: b7d4e91a5c33
Create Date: 2026-08-20 12:08:36.577756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa93d2683eaa'
down_revision: Union[str, None] = 'b7d4e91a5c33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Autogenerate produced `nullable=False` with no default for
    # product_type/is_taxable, which fails against a products table that
    # already has rows (adjusted by hand, same two-step pattern as
    # 205f1c3347a5/c08912894e62): add each with a server-side default so
    # existing rows backfill (every existing product is real physical
    # stock, i.e. GOODS, and was taxable exactly as its current tax_percent
    # already says), then drop the server default so the column matches
    # the model (client-side default only, applied on INSERT going
    # forward).
    product_type_enum = sa.Enum('GOODS', 'SERVICE', 'EXPENSE', name='product_type')
    product_type_enum.create(op.get_bind())
    op.add_column('products', sa.Column(
        'product_type', product_type_enum, nullable=False, server_default='GOODS'))
    op.alter_column('products', 'product_type', server_default=None)
    op.add_column('products', sa.Column('sub_unit_id', sa.UUID(), nullable=True))
    op.add_column('products', sa.Column('sub_unit_conversion_factor', sa.Numeric(precision=14, scale=6), nullable=True))
    op.add_column('products', sa.Column('tertiary_unit_id', sa.UUID(), nullable=True))
    op.add_column('products', sa.Column('tertiary_unit_conversion_factor', sa.Numeric(precision=14, scale=6), nullable=True))
    op.add_column('products', sa.Column('is_taxable', sa.Boolean(), nullable=False,
                                        server_default=sa.text('true')))
    op.alter_column('products', 'is_taxable', server_default=None)
    op.add_column('products', sa.Column('hsn_code', sa.String(length=32), nullable=True))
    op.add_column('products', sa.Column('size', sa.String(length=64), nullable=True))
    op.add_column('products', sa.Column('color', sa.String(length=64), nullable=True))
    op.add_column('products', sa.Column('flavour', sa.String(length=64), nullable=True))
    op.add_column('products', sa.Column('dftqc_no', sa.String(length=64), nullable=True))
    op.add_column('products', sa.Column('country_of_origin', sa.String(length=100), nullable=True))
    op.add_column('products', sa.Column('expiry_date', sa.Date(), nullable=True))
    op.create_index('ix_products_org_type', 'products', ['organization_id', 'product_type'], unique=False)
    # Named explicitly (autogenerate left these anonymous) so downgrade()
    # can drop them by name instead of an invalid drop_constraint(None, ...).
    op.create_foreign_key('products_sub_unit_id_fkey', 'products', 'units',
                          ['sub_unit_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('products_tertiary_unit_id_fkey', 'products', 'units',
                          ['tertiary_unit_id'], ['id'], ondelete='RESTRICT')
    op.create_check_constraint('ck_products_non_taxable_has_zero_tax', 'products', 'is_taxable OR tax_percent = 0')
    op.create_check_constraint('ck_products_sub_unit_conversion_paired', 'products', '(sub_unit_id IS NULL) = (sub_unit_conversion_factor IS NULL)')
    op.create_check_constraint('ck_products_sub_unit_conversion_positive', 'products', 'sub_unit_conversion_factor IS NULL OR sub_unit_conversion_factor > 0')
    op.create_check_constraint('ck_products_sub_unit_differs_from_unit', 'products', 'sub_unit_id IS NULL OR sub_unit_id != unit_id')
    op.create_check_constraint('ck_products_tertiary_unit_conversion_paired', 'products', '(tertiary_unit_id IS NULL) = (tertiary_unit_conversion_factor IS NULL)')
    op.create_check_constraint('ck_products_tertiary_unit_conversion_positive', 'products', 'tertiary_unit_conversion_factor IS NULL OR tertiary_unit_conversion_factor > 0')
    op.create_check_constraint('ck_products_tertiary_unit_differs_from_sub_unit', 'products', 'tertiary_unit_id IS NULL OR sub_unit_id IS NULL OR tertiary_unit_id != sub_unit_id')
    op.create_check_constraint('ck_products_tertiary_unit_differs_from_unit', 'products', 'tertiary_unit_id IS NULL OR tertiary_unit_id != unit_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_products_tertiary_unit_differs_from_unit', 'products', type_='check')
    op.drop_constraint('ck_products_tertiary_unit_differs_from_sub_unit', 'products', type_='check')
    op.drop_constraint('ck_products_tertiary_unit_conversion_positive', 'products', type_='check')
    op.drop_constraint('ck_products_tertiary_unit_conversion_paired', 'products', type_='check')
    op.drop_constraint('ck_products_sub_unit_differs_from_unit', 'products', type_='check')
    op.drop_constraint('ck_products_sub_unit_conversion_positive', 'products', type_='check')
    op.drop_constraint('ck_products_sub_unit_conversion_paired', 'products', type_='check')
    op.drop_constraint('ck_products_non_taxable_has_zero_tax', 'products', type_='check')
    op.drop_constraint('products_tertiary_unit_id_fkey', 'products', type_='foreignkey')
    op.drop_constraint('products_sub_unit_id_fkey', 'products', type_='foreignkey')
    op.drop_index('ix_products_org_type', table_name='products')
    op.drop_column('products', 'expiry_date')
    op.drop_column('products', 'country_of_origin')
    op.drop_column('products', 'dftqc_no')
    op.drop_column('products', 'flavour')
    op.drop_column('products', 'color')
    op.drop_column('products', 'size')
    op.drop_column('products', 'hsn_code')
    op.drop_column('products', 'is_taxable')
    op.drop_column('products', 'tertiary_unit_conversion_factor')
    op.drop_column('products', 'tertiary_unit_id')
    op.drop_column('products', 'sub_unit_conversion_factor')
    op.drop_column('products', 'sub_unit_id')
    op.drop_column('products', 'product_type')
    # Adjusted by hand: drop_column doesn't drop the Postgres native enum
    # type it created — same reasoning as c9791cffd8b9's product_status
    # downgrade — without this, re-running upgrade after this downgrade
    # fails with "type product_type already exists".
    sa.Enum(name='product_type').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
