"""add purchasing: suppliers, purchase orders, goods receipts, purchase returns

Revision ID: ae0be6ce7951
Revises: 69ff54a9f513
Create Date: 2026-08-14 08:34:46.337144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae0be6ce7951'
down_revision: Union[str, None] = '69ff54a9f513'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suppliers',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('contact_person', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('tax_id', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(trim(name)) > 0', name='ck_suppliers_name_not_blank'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_suppliers_org_name', 'suppliers', ['organization_id', 'name'], unique=False)
    op.create_table('purchase_orders',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'APPROVED', 'PARTIALLY_RECEIVED', 'RECEIVED', 'CANCELLED', name='purchase_order_status'), nullable=False),
    sa.Column('expected_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_purchase_orders_org_status', 'purchase_orders', ['organization_id', 'status'], unique=False)
    op.create_index('ix_purchase_orders_org_supplier', 'purchase_orders', ['organization_id', 'supplier_id'], unique=False)
    op.create_table('goods_receipts',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('purchase_order_id', sa.UUID(), nullable=False),
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('received_by', sa.UUID(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['received_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_goods_receipts_org_purchase_order', 'goods_receipts', ['organization_id', 'purchase_order_id'], unique=False)
    op.create_table('purchase_order_items',
    sa.Column('purchase_order_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('quantity_ordered', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('quantity_received', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity_ordered > 0', name='ck_po_items_quantity_ordered_positive'),
    sa.CheckConstraint('quantity_received <= quantity_ordered', name='ck_po_items_quantity_received_not_exceed_ordered'),
    sa.CheckConstraint('quantity_received >= 0', name='ck_po_items_quantity_received_non_negative'),
    sa.CheckConstraint('tax_percent >= 0 AND tax_percent <= 100', name='ck_po_items_tax_percent_range'),
    sa.CheckConstraint('unit_price >= 0', name='ck_po_items_unit_price_non_negative'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_po_items_product_id', 'purchase_order_items', ['product_id'], unique=False)
    op.create_index('ix_po_items_purchase_order_id', 'purchase_order_items', ['purchase_order_id'], unique=False)
    op.create_table('goods_receipt_items',
    sa.Column('goods_receipt_id', sa.UUID(), nullable=False),
    sa.Column('purchase_order_item_id', sa.UUID(), nullable=False),
    sa.Column('quantity_received', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('inventory_transaction_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('quantity_received > 0', name='ck_goods_receipt_items_quantity_positive'),
    sa.ForeignKeyConstraint(['goods_receipt_id'], ['goods_receipts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['inventory_transaction_id'], ['inventory_transactions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['purchase_order_item_id'], ['purchase_order_items.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inventory_transaction_id')
    )
    op.create_index('ix_goods_receipt_items_goods_receipt_id', 'goods_receipt_items', ['goods_receipt_id'], unique=False)
    op.create_table('purchase_returns',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('purchase_order_id', sa.UUID(), nullable=False),
    sa.Column('purchase_order_item_id', sa.UUID(), nullable=False),
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('returned_by', sa.UUID(), nullable=False),
    sa.Column('inventory_transaction_id', sa.UUID(), nullable=False),
    sa.Column('returned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('length(trim(reason)) > 0', name='ck_purchase_returns_reason_not_blank'),
    sa.CheckConstraint('quantity > 0', name='ck_purchase_returns_quantity_positive'),
    sa.ForeignKeyConstraint(['inventory_transaction_id'], ['inventory_transactions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['purchase_order_item_id'], ['purchase_order_items.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['returned_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inventory_transaction_id')
    )
    op.create_index('ix_purchase_returns_org_purchase_order', 'purchase_returns', ['organization_id', 'purchase_order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_purchase_returns_org_purchase_order', table_name='purchase_returns')
    op.drop_table('purchase_returns')
    op.drop_index('ix_goods_receipt_items_goods_receipt_id', table_name='goods_receipt_items')
    op.drop_table('goods_receipt_items')
    op.drop_index('ix_po_items_purchase_order_id', table_name='purchase_order_items')
    op.drop_index('ix_po_items_product_id', table_name='purchase_order_items')
    op.drop_table('purchase_order_items')
    op.drop_index('ix_goods_receipts_org_purchase_order', table_name='goods_receipts')
    op.drop_table('goods_receipts')
    op.drop_index('ix_purchase_orders_org_supplier', table_name='purchase_orders')
    op.drop_index('ix_purchase_orders_org_status', table_name='purchase_orders')
    op.drop_table('purchase_orders')
    # Adjusted by hand: drop_table() does not drop the Postgres native enum
    # type it created — without this, re-running upgrade after this
    # downgrade fails with "type purchase_order_status already exists"
    # (same fix as product_status in c9791cffd8b9).
    sa.Enum(name='purchase_order_status').drop(op.get_bind(), checkfirst=True)
    op.drop_index('ix_suppliers_org_name', table_name='suppliers')
    op.drop_table('suppliers')
    # ### end Alembic commands ###
