"""add sales: customers, sales orders, invoices, payments, sales returns

Revision ID: b6ce0b34f974
Revises: ae0be6ce7951
Create Date: 2026-08-14 08:53:02.050950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6ce0b34f974'
down_revision: Union[str, None] = 'ae0be6ce7951'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('contact_person', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('tax_id', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(trim(name)) > 0', name='ck_customers_name_not_blank'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_customers_org_name', 'customers', ['organization_id', 'name'], unique=False)
    op.create_table('invoice_sequences',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('next_value', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('organization_id')
    )
    op.create_table('sales_orders',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'CONFIRMED', 'FULFILLED', 'COMPLETED', 'CANCELLED', name='sales_order_status'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('confirmed_by', sa.UUID(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['confirmed_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sales_orders_org_customer', 'sales_orders', ['organization_id', 'customer_id'], unique=False)
    op.create_index('ix_sales_orders_org_status', 'sales_orders', ['organization_id', 'status'], unique=False)
    op.create_table('invoices',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('sales_order_id', sa.UUID(), nullable=False),
    sa.Column('invoice_number', sa.String(length=64), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('generated_by', sa.UUID(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('subtotal >= 0', name='ck_invoices_subtotal_non_negative'),
    sa.CheckConstraint('tax_amount >= 0', name='ck_invoices_tax_amount_non_negative'),
    sa.CheckConstraint('total_amount >= 0', name='ck_invoices_total_amount_non_negative'),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sales_order_id'], ['sales_orders.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sales_order_id')
    )
    op.create_index('ix_invoices_org_invoice_number', 'invoices', ['organization_id', 'invoice_number'], unique=True)
    op.create_table('sales_order_items',
    sa.Column('sales_order_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('quantity_ordered', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('quantity_fulfilled', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity_fulfilled <= quantity_ordered', name='ck_so_items_quantity_fulfilled_not_exceed_ordered'),
    sa.CheckConstraint('quantity_fulfilled >= 0', name='ck_so_items_quantity_fulfilled_non_negative'),
    sa.CheckConstraint('quantity_ordered > 0', name='ck_so_items_quantity_ordered_positive'),
    sa.CheckConstraint('tax_percent >= 0 AND tax_percent <= 100', name='ck_so_items_tax_percent_range'),
    sa.CheckConstraint('unit_price >= 0', name='ck_so_items_unit_price_non_negative'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sales_order_id'], ['sales_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_so_items_product_id', 'sales_order_items', ['product_id'], unique=False)
    op.create_index('ix_so_items_sales_order_id', 'sales_order_items', ['sales_order_id'], unique=False)
    op.create_table('payments',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('method', sa.Enum('CASH', 'CARD', 'BANK_TRANSFER', 'CHEQUE', 'OTHER', name='payment_method'), nullable=False),
    sa.Column('recorded_by', sa.UUID(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_payments_amount_positive'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_payments_org_invoice_id', 'payments', ['organization_id', 'invoice_id'], unique=False)
    op.create_table('sales_returns',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('sales_order_id', sa.UUID(), nullable=False),
    sa.Column('sales_order_item_id', sa.UUID(), nullable=False),
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('returned_by', sa.UUID(), nullable=False),
    sa.Column('inventory_transaction_id', sa.UUID(), nullable=False),
    sa.Column('returned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('length(trim(reason)) > 0', name='ck_sales_returns_reason_not_blank'),
    sa.CheckConstraint('quantity > 0', name='ck_sales_returns_quantity_positive'),
    sa.ForeignKeyConstraint(['inventory_transaction_id'], ['inventory_transactions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['returned_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sales_order_id'], ['sales_orders.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sales_order_item_id'], ['sales_order_items.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inventory_transaction_id')
    )
    op.create_index('ix_sales_returns_org_sales_order', 'sales_returns', ['organization_id', 'sales_order_id'], unique=False)
    # Adjusted by hand: autogenerate can't know this table already has rows
    # in a real deployment — a NOT NULL column added with no default would
    # fail on every existing row. server_default matches the ORM model's
    # client-side default="INV-".
    op.add_column('organizations', sa.Column('invoice_number_prefix', sa.String(length=20),
                                              server_default='INV-', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'invoice_number_prefix')
    op.drop_index('ix_sales_returns_org_sales_order', table_name='sales_returns')
    op.drop_table('sales_returns')
    op.drop_index('ix_payments_org_invoice_id', table_name='payments')
    op.drop_table('payments')
    # Adjusted by hand: drop_table() does not drop the Postgres native enum
    # type it created — without this, re-running upgrade after this
    # downgrade fails with "type payment_method already exists" (same fix
    # as product_status in c9791cffd8b9).
    sa.Enum(name='payment_method').drop(op.get_bind(), checkfirst=True)
    op.drop_index('ix_so_items_sales_order_id', table_name='sales_order_items')
    op.drop_index('ix_so_items_product_id', table_name='sales_order_items')
    op.drop_table('sales_order_items')
    op.drop_index('ix_invoices_org_invoice_number', table_name='invoices')
    op.drop_table('invoices')
    op.drop_index('ix_sales_orders_org_status', table_name='sales_orders')
    op.drop_index('ix_sales_orders_org_customer', table_name='sales_orders')
    op.drop_table('sales_orders')
    # Same enum-type-cleanup fix as payment_method above.
    sa.Enum(name='sales_order_status').drop(op.get_bind(), checkfirst=True)
    op.drop_table('invoice_sequences')
    op.drop_index('ix_customers_org_name', table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
