"""add product catalog: categories, brands, units, products

Revision ID: c9791cffd8b9
Revises: 205f1c3347a5
Create Date: 2026-08-13 21:02:36.195010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9791cffd8b9'
down_revision: Union[str, None] = '205f1c3347a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(trim(name)) > 0', name='ck_brands_name_not_blank'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_brands_org_name', 'brands', ['organization_id', 'name'], unique=True)
    op.create_table('categories',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(trim(name)) > 0', name='ck_categories_name_not_blank'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_categories_org_name', 'categories', ['organization_id', 'name'], unique=True)
    op.create_table('units',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('abbreviation', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(trim(abbreviation)) > 0', name='ck_units_abbreviation_not_blank'),
    sa.CheckConstraint('length(trim(name)) > 0', name='ck_units_name_not_blank'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_units_org_abbreviation', 'units', ['organization_id', 'abbreviation'], unique=True)
    op.create_index('ix_units_org_name', 'units', ['organization_id', 'name'], unique=True)
    op.create_table('products',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('barcode', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('brand_id', sa.UUID(), nullable=True),
    sa.Column('unit_id', sa.UUID(), nullable=False),
    sa.Column('purchase_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('selling_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('minimum_stock_level', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'ARCHIVED', name='product_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(trim(name)) > 0', name='ck_products_name_not_blank'),
    sa.CheckConstraint('length(trim(sku)) > 0', name='ck_products_sku_not_blank'),
    sa.CheckConstraint('minimum_stock_level >= 0', name='ck_products_minimum_stock_level_non_negative'),
    sa.CheckConstraint('purchase_price >= 0', name='ck_products_purchase_price_non_negative'),
    sa.CheckConstraint('selling_price >= 0', name='ck_products_selling_price_non_negative'),
    sa.CheckConstraint('sku = upper(sku)', name='ck_products_sku_uppercase'),
    sa.CheckConstraint('tax_percent >= 0 AND tax_percent <= 100', name='ck_products_tax_percent_range'),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_products_brand_id', 'products', ['brand_id'], unique=False)
    op.create_index('ix_products_category_id', 'products', ['category_id'], unique=False)
    op.create_index('ix_products_org_barcode', 'products', ['organization_id', 'barcode'], unique=True, postgresql_where='barcode IS NOT NULL')
    op.create_index('ix_products_org_name', 'products', ['organization_id', 'name'], unique=False)
    op.create_index('ix_products_org_sku', 'products', ['organization_id', 'sku'], unique=True)
    op.create_index('ix_products_org_status', 'products', ['organization_id', 'status'], unique=False)
    op.create_index('ix_products_unit_id', 'products', ['unit_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_products_unit_id', table_name='products')
    op.drop_index('ix_products_org_status', table_name='products')
    op.drop_index('ix_products_org_sku', table_name='products')
    op.drop_index('ix_products_org_name', table_name='products')
    op.drop_index('ix_products_org_barcode', table_name='products', postgresql_where='barcode IS NOT NULL')
    op.drop_index('ix_products_category_id', table_name='products')
    op.drop_index('ix_products_brand_id', table_name='products')
    op.drop_table('products')
    # Adjusted by hand: drop_table('products') does not drop the Postgres
    # native enum type it created — without this, re-running upgrade after
    # this downgrade fails with "type product_status already exists".
    sa.Enum(name='product_status').drop(op.get_bind(), checkfirst=True)
    op.drop_index('ix_units_org_name', table_name='units')
    op.drop_index('ix_units_org_abbreviation', table_name='units')
    op.drop_table('units')
    op.drop_index('ix_categories_org_name', table_name='categories')
    op.drop_table('categories')
    op.drop_index('ix_brands_org_name', table_name='brands')
    op.drop_table('brands')
    # ### end Alembic commands ###
