"""add phone, email, website to organizations

Revision ID: da68ba14a399
Revises: 8e90faa79337
Create Date: 2026-08-14 09:41:43.085307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da68ba14a399'
down_revision: Union[str, None] = '8e90faa79337'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('phone', sa.String(length=32), nullable=True))
    op.add_column('organizations', sa.Column('email', sa.String(length=320), nullable=True))
    op.add_column('organizations', sa.Column('website', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'website')
    op.drop_column('organizations', 'email')
    op.drop_column('organizations', 'phone')
    # ### end Alembic commands ###
